-- ════════════════════════════════════════════════════════════════════════
--  Vegan Oji — `recipes` table (Supabase / Postgres)
--  ⚠️  TODO: NOT WIRED YET. The live page currently reads recipes.json.
--      When a Supabase project exists: run this, run `node seed.mjs`, then
--      flip the page's data source (see recipes/README.md → "Switch to Supabase").
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.recipes (
  id             bigint generated by default as identity primary key,
  slug           text        not null unique,
  title_jp       text        not null,           -- plain kanji (used by the export card)
  title_furigana text,                            -- ruby HTML for the page heading
  hero_image_url text,
  category       text        not null,            -- shusai | fukusai | shirumono | gohan | sweets
  time_min       int,
  servings       text,
  ingredients    jsonb       not null default '[]'::jsonb,  -- [{ "item": ruby-html, "amount": ruby-html }]
  steps          jsonb       not null default '[]'::jsonb,  -- [ ruby-html string ]
  source_name    text,
  source_url     text,
  tips           jsonb       not null default '[]'::jsonb,  -- [ ruby-html string ]  (Oji's tips)
  created_at     timestamptz not null default now(),
  published      boolean     not null default false
);

-- The public site only ever reads published rows.
alter table public.recipes enable row level security;

drop policy if exists "public read published recipes" on public.recipes;
create policy "public read published recipes"
  on public.recipes
  for select
  using ( published = true );

create index if not exists recipes_published_category_idx
  on public.recipes (category)
  where published;
